### ISSUE TITLE
Please remove the dependency restriction on latest numpy, pytorch, and pydantic

### ISSUE THREAD

**Issue by AndyJZhao** [TattaBio/DGEB#19]
The requirements of DGEB is pretty strict and it breaks a lot of things.

- Numpy>=2.0.0 conflicts with huggingface dataset package.
- pydantic>=2.7.4 conflicts with pytorch-lightning.
- torch>=2.3.1 is also very new and will lead to compatibility issues.

Please kindly remove those dependency restrictions or use `some_package>=the_oldest_supported_version`.

**Comment by scopello** [comment]
Thanks for bringing this up, fixed in #20
